channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.3
- pip:
  - mlflow==2.13.1
  - attrs==25.4.0
  - cloudpickle==3.1.2
  - matplotlib==3.10.7
  - numpy==1.26.4
  - nvidia-ml-py==13.580.82
  - packaging==24.2
  - pandas==2.2.2
  - pytorch-lightning==2.3.0
  - pyyaml==6.0.3
  - rich==14.2.0
  - scipy==1.16.3
  - torch==2.6.0
  - torchvision==0.21.0
name: mlflow-env
